# Generated by Django 4.1.4 on 2022-12-29 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statue",
                    models.CharField(
                        choices=[
                            ("i", "instance"),
                            ("a", "accepted"),
                            ("p", "in progress"),
                            ("t", "terminated"),
                            ("c", "canceled"),
                        ],
                        default="i",
                        max_length=1,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("forecolor", models.CharField(max_length=10, null=True)),
                ("backcolor", models.CharField(max_length=10, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_lat",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "origin_lng",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "destination_lat",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "destination_lng",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                ("origin_address", models.TextField()),
                ("destination_address", models.TextField()),
                (
                    "distance",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "duration",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAttachement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_docs",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
