# Generated by Django 4.1.4 on 2022-12-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_backcolor_task_finished_at_task_forecolor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLocation",
            fields=[
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="parcours",
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                (
                    "start_lat",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "start_lng",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "end_lat",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                (
                    "end_lng",
                    models.DecimalField(decimal_places=20, max_digits=50, null=True),
                ),
                ("start_address", models.TextField()),
                ("end_address", models.TextField()),
            ],
        ),
    ]
