# Generated by Django 4.1.4 on 2022-12-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_tasklocation_taskattachement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklocation",
            old_name="end_address",
            new_name="destination_address",
        ),
        migrations.RenameField(
            model_name="tasklocation",
            old_name="end_lat",
            new_name="destination_lat",
        ),
        migrations.RenameField(
            model_name="tasklocation",
            old_name="end_lng",
            new_name="destination_lng",
        ),
        migrations.RenameField(
            model_name="tasklocation",
            old_name="start_address",
            new_name="origin_address",
        ),
        migrations.RenameField(
            model_name="tasklocation",
            old_name="start_lat",
            new_name="origin_lat",
        ),
        migrations.RenameField(
            model_name="tasklocation",
            old_name="start_lng",
            new_name="origin_lng",
        ),
    ]
