# Generated by Django 4.1.4 on 2022-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_rename_end_address_tasklocation_destination_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklocation",
            name="distance",
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
    ]
