# Generated by Django 4.1.4 on 2022-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_tasklocation_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklocation",
            name="duration",
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
    ]
