# Generated by Django 4.1.4 on 2022-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unite", models.CharField(max_length=15)),
                ("symbole", models.CharField(max_length=15)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=3, default=1, max_digits=8),
                ),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
