# Generated by Django 4.1.4 on 2022-12-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_category_alter_unite_category_subcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unite",
            old_name="unite",
            new_name="name",
        ),
    ]
