# Generated by Django 4.1.4 on 2022-12-11 13:40

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
        (
            "commercials",
            "0008_tier_rename_date_creation_stockmovement_created_at_and_more",
        ),
        ("stock", "0004_alter_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("P", "Product"),
                            ("RM", "Raw Material"),
                            ("FP", "Final product"),
                            ("SFP", "Semi Finished product"),
                            ("S", "Service"),
                        ],
                        default="P",
                        max_length=3,
                    ),
                ),
                ("stock_qte", apps.application.fileds.DecimalField()),
                ("unite_coef", apps.application.fileds.DecimalField()),
                ("unite_value", apps.application.fileds.DecimalField()),
                ("stock_value", apps.application.fileds.DecimalField()),
                ("supply_qte", apps.application.fileds.DecimalField()),
                ("min_qte", apps.application.fileds.DecimalField()),
                ("purchase_period", models.IntegerField(default=30)),
                ("purchase_rate", models.FloatField(default=5)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.category",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="commercials.tier",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provides",
                        to="commercials.tier",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.subcategory",
                    ),
                ),
                (
                    "tva",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.tva",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.unite",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
