# Generated by Django 4.1.4 on 2022-12-11 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="update_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
