# Generated by Django 4.1.4 on 2022-12-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_product_update_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
