# Generated by Django 4.1.4 on 2022-12-12 08:28

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", apps.application.fileds.DecimalField()),
                ("value", apps.application.fileds.DecimalField()),
                ("out", models.BooleanField(default=False)),
                ("document", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sock_movements",
                        to="stock.product",
                    ),
                ),
            ],
        ),
    ]
