# Generated by Django 4.1.4 on 2022-12-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_movement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movement",
            new_name="StockMovement",
        ),
    ]
