# Generated by Django 4.1.4 on 2022-12-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_rename_movement_stockmovement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="maker",
        ),
        migrations.RemoveField(
            model_name="product",
            name="provider",
        ),
    ]
