# Generated by Django 4.1.4 on 2022-12-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accountings", "0001_initial"),
        ("stock", "0010_remove_product_maker_remove_product_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="maker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="accountings.third",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provides",
                to="accountings.third",
            ),
        ),
    ]
