# Generated by Django 4.1.4 on 2022-12-13 08:27

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_product_maker_product_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", apps.application.fileds.DecimalField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compositions",
                        to="stock.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
