# Generated by Django 4.1.4 on 2022-12-13 10:58

import apps.application.fileds
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0014_remove_product_min_qte_remove_product_stock_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_value",
            field=apps.application.fileds.DecimalField(default=0),
            preserve_default=False,
        ),
    ]
