# Generated by Django 4.1.4 on 2022-12-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="autre",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
