# Generated by Django 4.1.4 on 2022-12-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_profile_autre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="autre",
        ),
    ]
