# Generated by Django 4.1.4 on 2022-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_alter_localisation_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="additional",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
