# Generated by Django 4.1.4 on 2023-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_profile_statue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="statue",
            field=models.CharField(
                choices=[
                    ("u", "undefined"),
                    ("a", "active"),
                    ("n", "non active"),
                    ("ab", "absent"),
                ],
                default="u",
                max_length=2,
            ),
        ),
    ]
