# Generated by Django 4.1.3 on 2022-12-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_discussion_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="utilisateur",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="messagevue",
            old_name="utilisateur",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="utilisateur",
            new_name="user",
        ),
    ]
