# Generated by Django 4.1.4 on 2022-12-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_profile"),
        ("chats", "0005_rename_user_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_messages",
                to="general.profile",
            ),
        ),
        migrations.AlterField(
            model_name="messagevue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mes_vues",
                to="general.profile",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participations",
                to="general.profile",
            ),
        ),
    ]
