# Generated by Django 4.1.4 on 2022-12-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_alter_message_sender_alter_messagevue_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Utilisateur",
        ),
    ]
