# Generated by Django 4.1.4 on 2022-12-29 09:01

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Third",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("debit", apps.application.fileds.AppDecimalField()),
                ("credit", apps.application.fileds.AppDecimalField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("c", "client"),
                            ("p", "provider"),
                            ("f", "fabricant"),
                            ("t", "third"),
                        ],
                        default="t",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("amount", apps.application.fileds.AppDecimalField()),
                ("out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "third",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accountings.third",
                    ),
                ),
            ],
        ),
    ]
