# Generated by Django 4.1.4 on 2022-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_managments", "0002_localisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="type",
            field=models.CharField(
                choices=[("D", "DRIVER"), ("A", "ADMINISTRATION"), ("O", "OTHER")],
                default="O",
                max_length=2,
            ),
        ),
    ]
