# Generated by Django 4.1.4 on 2022-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tva", models.CharField(max_length=50, unique=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=3, default=0.19, max_digits=5),
                ),
            ],
        ),
    ]
