# Generated by Django 4.1.3 on 2022-12-06 09:46

import apps.application.fileds
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("qte_stock", apps.application.fileds.AppDecimalField()),
                ("pre_qte_stock", apps.application.fileds.AppDecimalField()),
                ("value", apps.application.fileds.AppDecimalField()),
                ("pre_value", apps.application.fileds.AppDecimalField()),
            ],
        ),
    ]
