# Generated by Django 4.1.3 on 2022-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commercials",
            "0002_alter_product_pre_qte_stock_alter_product_pre_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unite",
            field=models.CharField(default="unite", max_length=10),
        ),
    ]
