# Generated by Django 4.1.3 on 2022-12-06 13:30

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commercials", "0003_product_unite"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailReception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", apps.application.fileds.AppDecimalField()),
                ("prix_unite", apps.application.fileds.AppDecimalField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptions",
                        to="commercials.product",
                    ),
                ),
            ],
        ),
    ]
