# Generated by Django 4.1.3 on 2022-12-06 13:41

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commercials", "0004_detailreception"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qte", apps.application.fileds.AppDecimalField()),
                ("prix_unite", apps.application.fileds.AppDecimalField()),
                ("out", models.BooleanField()),
                ("document", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="commercials.product",
                    ),
                ),
            ],
        ),
    ]
