# Generated by Django 4.1.3 on 2022-12-06 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("commercials", "0005_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
