# Generated by Django 4.1.3 on 2022-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercials", "0006_stockmovement_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="out",
            field=models.BooleanField(default=False),
        ),
    ]
