# Generated by Django 4.1.3 on 2022-12-08 06:31

import apps.application.fileds
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commercials", "0007_alter_stockmovement_out"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("debit", apps.application.fileds.AppDecimalField()),
                ("credit", apps.application.fileds.AppDecimalField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("c", "client"),
                            ("p", "provider"),
                            ("f", "fabricant"),
                            ("t", "tier"),
                        ],
                        default="t",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="stockmovement",
            old_name="date_creation",
            new_name="created_at",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("montant", apps.application.fileds.AppDecimalField()),
                ("out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="commercials.tier",
                    ),
                ),
            ],
        ),
    ]
