# Generated by Django 4.1.4 on 2022-12-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0010_remove_product_maker_remove_product_provider"),
        (
            "commercials",
            "0008_tier_rename_date_creation_stockmovement_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.AlterField(
            model_name="detailreception",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receptions",
                to="stock.product",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
        migrations.DeleteModel(
            name="Tier",
        ),
    ]
